//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ?肩g#H蜟/Bm0琮{E8誰i??鲵绒???鋷鷤€?X鋰膢	榃骥钞瀉?o咎}瓊?V顡$蝮??p|:tM=^?fi%?%靾鱮肄磧雰+?蘻&gt;?$鍠澍傼靗逈3哸坚_蹻蔊杀0€瘭?鸹軃L?菍???^&apos;岜倔?媅h&amp;9-_狐螢_鷺/牘瑀3嗕抌3傟頜0聝[护?鲫
        ///2!伥篹瀎&quot;澒Lw&gt;粛&quot;踃N齊胉&gt;^?x烊開&quot;d[?冣艰?撪E客?せ?瞣??蠲痧T?D?aT揶p$瘂伣螰\?.w?蜎:违+?较趇3噬_XR?亶鞝础脂N沿鶠s瀶柭g\邦楻攄&amp;w%偛宁?b輠C祔攟??檴鑂?&apos;A捄/Q	?槪棻S.	⑸%O?6uK%5?&quot;G?諗荢3?拱軎-@愾%鈉{吢L攎f嫃冴$f/??れ?健?棃斧?⑿O?蠖濟&quot;.鍉馊,=?鍢跴=?1脴?r抑俪茙只?&gt;?LF&amp;?oCl?奢Id:!珋]&amp;砬怯*\?/漿=佮X挑`嘡;葭P哣W&quot;n\n杙鮪O葼^扒蕵礊}萕_^\&amp;挦?瀫%o诠邪Px铪⒃礿5臧:?k８$m?紌颡鞢*?庬燗廴g縎纡掕f%p3捦h晙p吠$怘頭r 完鋡E@?-晭訝泫蓻鯹掁:c矪H [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string stage {
            get {
                return ResourceManager.GetString("stage", resourceCulture);
            }
        }
    }
}
